export enum Work {
    innerWork = 'Внутренняя работа',
    administrativeMatters = "Административные вопросы",
    NIOKR = "НИОКР",
    TKP = "ТКП",
    service = "сервис",
    study = "Обучение",
    currentWork = "Текущие работы",
    accounting = "Бухучет",
    AHO = "АХО",
    finance = "Финансы",
    agreements = "Договора",
    tender = "Тендер",
    marketing = "Маркетинг",
    projectOffice = "Проектный офис",
    objectDuty = "Дежурство на объекте",
    callWaiting = "Ожидание вызова",
    dedicatedWork = "Выделенная работа",
    economist = "Экономист",
    personnelWork = "Работа по кадрам",
    workOnTB = "Работа по ТБ",
    other = "другое"
}